<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projekt</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cerulean/bootstrap.min.css" integrity="sha384-3fdgwJw17Bi87e1QQ4fsLn4rUFqWw//KU0g8TvV6quvahISRewev6/EocKNuJmEw" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css "> <!-- kdyztak tady -->
</head>
<body>
    <?php session_start();?>


    
    <header>
        <ul class="navigace">
            <li ><a href="index.php">Úvod</a></li>
            <?php
            if(isset($_SESSION["uzivatel"]))
                if($_SESSION["uzivatel"]["role"]<=3){
            ?>
                <li><a href="rezervace.php">Rezervace</a></li>
            <?php
            }
            ?>
            <li><a href="fotky.php">Fotky</a></li>
                <?php if (!isset($_SESSION["uzivatel"])) { ?> 
                    <li><a class="prihlas" href="login.php">přihlásit se</a></li>
                    <?php } ?>
                <?php if (isset($_SESSION["uzivatel"])) { ?> 
                    <li><a class="prihlas" href="logout.php">Odhlásit se</a></li>
                    <?php } ?>
            
            <!--<li class="golem"><img class="o_golem"src="obrazky/obrazek_projekt_gym.png" alt="golem"></a></li>-->
        </ul>
        
    </header>
    <div class="body">

         